# Generated by Django 5.1.15 on 2026-09-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_starter_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='archetype',
            field=models.CharField(choices=[('employee', 'Employee'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], help_text="Which of the frontend's 4 known UI archetypes this role renders as. The frontend is unmodified and only understands these 4 (see docs/TASKS.md P1-E3-01) so every role — starter or custom — must declare one, even a brand-new custom role.", max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
