# Generated by Django 5.1.15 on 2026-09-18 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_role_archetype_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='archetype',
            field=models.CharField(choices=[('employee', 'Employee'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], help_text="Which of the frontend's 3 known UI archetypes this role renders as (employee/admin/superadmin — see core.enums.RoleArchetype for why not 4). The frontend is unmodified and only understands these 3 (docs/TASKS.md P1-E3-01) so every role — starter or custom — must declare one, even a brand-new custom role.", max_length=20),
        ),
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_fa_user_id_92c7c7_idx')],
            },
        ),
    ]
