# Generated by Django 5.1.15 on 2026-09-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_employee_self_write_grant"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
