# Generated by Django 6.0.5 on 2026-09-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_role_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="True when an admin has issued a temporary password: the user must change it (POST users/me/change-password) before using the app.",
            ),
        ),
    ]
