# Generated by Django 6.0.5 on 2026-09-25 12:49

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_passwordsetuptoken"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.models.CompatUserManager()),
            ],
        ),
    ]
