# Generated by Django 6.0.5 on 2026-09-25 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0006_grade_jobfamily_level_employee_grade_employee_level_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("promotion", "Promotion"),
                            ("dept_transfer", "Department transfer"),
                            ("location_transfer", "Location transfer"),
                            ("position_change", "Position change"),
                            ("manager_change", "Manager change"),
                        ],
                        max_length=20,
                    ),
                ),
                ("from_data", models.JSONField(blank=True, default=dict)),
                ("to_data", models.JSONField(blank=True, default=dict)),
                ("effective_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("effective", "Effective"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_changes",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date", "-created_at"],
            },
        ),
    ]
