"""Post-payroll outputs from a finalized run only (PAY-018, PAY-FR-026).
Every output stores version, period, generated by and generated time;
regeneration supersedes the previous version instead of overwriting it."""

import csv
import datetime
import io

from django.db import transaction
from django.utils import timezone

from payroll import models as m
from payroll.engine.money import ZERO, money_str

from .common import audit, conflict, invalid

ONES = [
    "",
    "One",
    "Two",
    "Three",
    "Four",
    "Five",
    "Six",
    "Seven",
    "Eight",
    "Nine",
    "Ten",
    "Eleven",
    "Twelve",
    "Thirteen",
    "Fourteen",
    "Fifteen",
    "Sixteen",
    "Seventeen",
    "Eighteen",
    "Nineteen",
]
TENS = ["", "", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety"]


def amount_in_words(value) -> str:
    """Indian numbering (lakh/crore), rupees only."""
    n = int(value)
    if n == 0:
        return "Rupees Zero Only"

    def two(x):
        return ONES[x] if x < 20 else (TENS[x // 10] + (" " + ONES[x % 10] if x % 10 else ""))

    def three(x):
        hundreds, rest = divmod(x, 100)
        parts = []
        if hundreds:
            parts.append(ONES[hundreds] + " Hundred")
        if rest:
            parts.append(two(rest))
        return " ".join(parts)

    parts = []
    crore, n = divmod(n, 10_000_000)
    lakh, n = divmod(n, 100_000)
    thousand, n = divmod(n, 1000)
    if crore:
        parts.append(three(crore) + " Crore")
    if lakh:
        parts.append(two(lakh) + " Lakh")
    if thousand:
        parts.append(two(thousand) + " Thousand")
    if n:
        parts.append(three(n))
    return "Rupees " + " ".join(parts) + " Only"


def _require_finalized(run):
    if run.status != "finalized":
        raise conflict(
            "Outputs can only be generated from a finalized (locked) payroll.",
            code="PAY_INVALID_STATE",
        )


def financial_year_start(period):
    return datetime.date(period.year if period.month >= 4 else period.year - 1, 4, 1)


def ytd_for(employee, period):
    """Year-to-date from released payslips in the financial year (Apr–Mar)."""
    start = financial_year_start(period)
    slips = m.Payslip.objects.filter(
        employee=employee,
        status="released",
        period__start_date__gte=start,
        period__end_date__lte=period.end_date,
    ).select_related("result")
    totals = {"gross": ZERO, "deductions": ZERO, "net": ZERO, "taxable": ZERO, "by_component": {}}
    for slip in slips:
        result = slip.result
        totals["gross"] += result.gross_earnings
        totals["deductions"] += result.total_deductions
        totals["net"] += result.net_pay
        for line in result.lines.all():
            if line.component_type == "earning" and line.is_taxable:
                totals["taxable"] += line.amount
            if line.component_type != "employer_contribution":
                totals["by_component"][line.component_code] = (
                    totals["by_component"].get(line.component_code, ZERO) + line.amount
                )
    return {
        "from": start.isoformat(),
        "to": period.end_date.isoformat(),
        "gross": money_str(totals["gross"]),
        "deductions": money_str(totals["deductions"]),
        "net": money_str(totals["net"]),
        "taxable": money_str(totals["taxable"]),
        "by_component": {k: money_str(v) for k, v in totals["by_component"].items()},
    }


def payslip_payload(result):
    period = result.run.period
    entity = period.pay_group.legal_entity
    profile = getattr(entity, "payroll_profile", None)
    snap = result.employee_snapshot
    lines = list(result.lines.all())

    def section(kind):
        return [
            {
                "code": ln.component_code,
                "name": ln.component_name,
                "amount": money_str(ln.amount),
                "basis": ln.calculation_basis,
            }
            for ln in lines
            if ln.component_type == kind and ln.show_on_payslip and ln.amount != 0
        ]

    return {
        "company": {
            "name": entity.name,
            "address": getattr(profile, "address", ""),
            "pan": getattr(profile, "pan", ""),
            "tan": getattr(profile, "tan", ""),
        },
        "employee": snap,
        "period": {
            "label": f"{datetime.date(period.year, period.month, 1):%B %Y}",
            "start": period.start_date.isoformat(),
            "end": period.end_date.isoformat(),
            "pay_date": period.pay_date.isoformat(),
        },
        "working_days": str(result.working_days),
        "payable_days": str(result.payable_days),
        "lop_days": str(result.lop_days),
        "earnings": section("earning"),
        "deductions": section("deduction"),
        "employer_contributions": section("employer_contribution"),
        "gross": money_str(result.gross_earnings),
        "total_deductions": money_str(result.total_deductions),
        "net_pay": money_str(result.net_pay),
        "net_pay_words": amount_in_words(result.net_pay),
        "bank": {
            "name": snap.get("bank_name", ""),
            "account": (
                ("XXXXXX" + snap.get("bank_account_last4", ""))
                if snap.get("bank_account_last4")
                else ""
            ),
        },
        "run_no": result.run.run_no,
    }


@transaction.atomic
def generate_payslips(run, actor):
    _require_finalized(run)
    count = 0
    for result in run.results.select_related("employee").prefetch_related("lines"):
        if result.is_on_hold:
            continue
        existing = m.Payslip.objects.filter(employee=result.employee, period=run.period).order_by(
            "-version"
        )
        latest = existing.first()
        if latest and latest.result_id == result.pk and latest.status != "superseded":
            continue  # idempotent: already generated for this run
        existing.exclude(status="superseded").update(
            status="superseded", superseded_at=timezone.now()
        )
        payload = payslip_payload(result)
        m.Payslip.objects.create(
            result=result,
            employee=result.employee,
            period=run.period,
            version=(latest.version + 1) if latest else 1,
            payload=payload,
            net_pay=result.net_pay,
            generated_by=actor,
        )
        count += 1
    audit(actor, "payslips.generated", run, count=count)
    return count


@transaction.atomic
def release_payslips(run, actor):
    _require_finalized(run)
    now = timezone.now()
    slips = m.Payslip.objects.filter(result__run=run, status="generated")
    if (
        not slips.exists()
        and not m.Payslip.objects.filter(result__run=run, status="released").exists()
    ):
        raise invalid("Generate payslips before releasing them.")
    count = slips.update(status="released", released_by=actor, released_at=now)
    for slip in m.Payslip.objects.filter(result__run=run, status="released"):
        slip.payload = {**slip.payload, "ytd": ytd_for(slip.employee, run.period)}
        slip.save(update_fields=["payload"])
    audit(actor, "payslips.released", run, count=count)
    return count


def _write(rows, header):
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow(header)
    writer.writerows(rows)
    return buffer.getvalue()


def _results(run):
    return (
        run.results.select_related("employee")
        .prefetch_related("lines")
        .order_by("employee__employee_code")
    )


def _amount(result, codes):
    return sum((ln.amount for ln in result.lines.all() if ln.component_code in codes), ZERO)


def _rule_codes(rule):
    return set(
        m.SalaryComponent.objects.filter(statutory_rule_code=rule).values_list("code", flat=True)
    )


def build_output(run, kind):
    period = run.period
    label = f"{period.year}{period.month:02d}"
    results = list(_results(run))
    if kind == "bank_advice":
        rows, total = [], ZERO
        for r in results:
            if r.is_on_hold or r.net_pay <= 0:
                continue
            info = getattr(r.employee, "payroll_payment_info", None)
            rows.append(
                [
                    r.employee.employee_code,
                    r.employee_snapshot.get("name"),
                    getattr(info, "bank_account_holder_name", ""),
                    getattr(info, "bank_name", ""),
                    getattr(info, "bank_account_number", ""),
                    getattr(info, "bank_ifsc_code", ""),
                    money_str(r.net_pay),
                    period.pay_date.isoformat(),
                    f"SALARY {label}",
                ]
            )
            total += r.net_pay
        header = [
            "employee_code",
            "employee_name",
            "account_holder",
            "bank_name",
            "account_number",
            "ifsc",
            "amount",
            "value_date",
            "narration",
        ]
        return _write(rows, header), len(rows), total, f"bank_advice_{label}.csv"
    if kind in ("statutory_pf", "statutory_esi", "statutory_pt", "statutory_tds", "statutory_lwf"):
        spec = {
            "statutory_pf": (["PF_EMPLOYEE"], ["PF_EMPLOYER"], "uan_number"),
            "statutory_esi": (["ESI_EMPLOYEE"], ["ESI_EMPLOYER"], "esi_number"),
            "statutory_pt": (["PT"], [], "professional_tax_state"),
            "statutory_tds": (["TDS"], [], "pan_number"),
            "statutory_lwf": (["LWF_EMPLOYEE"], ["LWF_EMPLOYER"], "lwf_applicable"),
        }[kind]
        # PF/ESI reports show the statutory wage base; others show gross earnings.
        wage_base = {
            "statutory_pf": set(
                m.SalaryComponent.objects.filter(include_in_pf_wage=True).values_list(
                    "code", flat=True
                )
            ),
            "statutory_esi": set(
                m.SalaryComponent.objects.filter(include_in_esi_wage=True).values_list(
                    "code", flat=True
                )
            ),
        }
        ee_codes = set().union(*[_rule_codes(c) for c in spec[0]]) if spec[0] else set()
        er_codes = set().union(*[_rule_codes(c) for c in spec[1]]) if spec[1] else set()
        rows, total = [], ZERO
        for r in results:
            ee, er = _amount(r, ee_codes), _amount(r, er_codes)
            if ee == 0 and er == 0:
                continue
            stat = getattr(r.employee, "payroll_statutory_info", None)
            wage_codes = wage_base.get(kind)
            wages = sum(
                (
                    ln.amount
                    for ln in r.lines.all()
                    if ln.component_type == "earning"
                    and (wage_codes is None or ln.component_code in wage_codes)
                ),
                ZERO,
            )
            rows.append(
                [
                    r.employee.employee_code,
                    r.employee_snapshot.get("name"),
                    getattr(stat, spec[2], "") if stat else "",
                    money_str(r.gross_earnings),
                    money_str(wages),
                    money_str(ee),
                    money_str(er),
                    money_str(ee + er),
                ]
            )
            total += ee + er
        header = [
            "employee_code",
            "employee_name",
            "identifier",
            "gross",
            "wages",
            "employee_share",
            "employer_share",
            "total",
        ]
        return _write(rows, header), len(rows), total, f"{kind}_{label}.csv"
    if kind == "journal":
        totals = {}
        for r in results:
            for line in r.lines.all():
                key = (line.component_code, line.component_name, line.component_type)
                totals[key] = totals.get(key, ZERO) + line.amount
        rows = []
        for (code, name, kind_), amount in sorted(totals.items()):
            if kind_ == "earning":
                rows.append([f"Salary expense - {name}", code, money_str(amount), ""])
            elif kind_ == "deduction":
                rows.append([f"Payable - {name}", code, "", money_str(amount)])
            else:
                rows.append([f"Employer expense - {name}", code, money_str(amount), ""])
                rows.append([f"Payable - {name} (employer)", code, "", money_str(amount)])
        net = sum((r.net_pay for r in results), ZERO)
        rows.append(["Net salary payable", "NET", "", money_str(net)])
        return (
            _write(rows, ["account", "component", "debit", "credit"]),
            len(rows),
            net,
            f"payroll_journal_{label}.csv",
        )
    raise invalid(f"Unknown output {kind}.")


@transaction.atomic
def generate_output(run, kind, actor):
    _require_finalized(run)
    content, count, total, file_name = build_output(run, kind)
    latest = run.outputs.filter(kind=kind).order_by("-version").first()
    run.outputs.filter(kind=kind).exclude(status="superseded").update(status="superseded")
    output = m.PayrollOutput.objects.create(
        run=run,
        kind=kind,
        version=(latest.version + 1) if latest else 1,
        file_name=file_name,
        content=content,
        record_count=count,
        total_amount=total,
        generated_by=actor,
    )
    audit(actor, "output.generated", output, kind=kind, version=output.version, records=count)
    return output


@transaction.atomic
def mark_paid(output, actor):
    if output.kind != "bank_advice" or output.status != "generated":
        raise conflict(
            "Only the current bank advice can be marked as paid.", code="PAY_INVALID_STATE"
        )
    output.status = "paid"
    output.paid_by = actor
    output.paid_at = timezone.now()
    output.save()
    audit(actor, "output.marked_paid", output, total=output.total_amount)
    return output


def checklist(run):
    if run is None:
        return []
    slips = m.Payslip.objects.filter(result__run=run)
    outputs = {o.kind: o for o in run.outputs.exclude(status="superseded")}
    approvals = list(run.approvals.all())

    def state(done):
        return "completed" if done else "pending"

    return [
        {
            "key": "register",
            "label": "Review Payroll Register",
            "status": state(run.status not in ("calculating", "created")),
        },
        {
            "key": "approvals",
            "label": "Approvals",
            "status": state(run.status in ("approved", "finalized")) if approvals else "pending",
        },
        {"key": "lock", "label": "Lock Payroll", "status": state(run.status == "finalized")},
        {
            "key": "payslips",
            "label": "Generate & Release Payslips",
            "status": (
                "completed"
                if slips.filter(status="released").exists()
                else ("in_progress" if slips.exists() else "pending")
            ),
        },
        {
            "key": "payments",
            "label": "Process Payments",
            "status": (
                "completed"
                if getattr(outputs.get("bank_advice"), "status", "") == "paid"
                else ("in_progress" if "bank_advice" in outputs else "pending")
            ),
        },
        {
            "key": "statutory",
            "label": "Statutory Reports",
            "status": state(any(k.startswith("statutory_") for k in outputs)),
        },
        {"key": "journal", "label": "Accounting Export", "status": state("journal" in outputs)},
    ]


@transaction.atomic
def complete_period(period, run, actor, notes=""):
    _require_finalized(run)
    if (
        not m.Payslip.objects.filter(result__run=run, status="released").exists()
        and run.results.filter(is_on_hold=False).exists()
    ):
        raise invalid("Release payslips before closing the payroll.")
    period.status = "completed"
    period.completed_by = actor
    period.completed_at = timezone.now()
    period.notes = notes or period.notes
    period.save()
    audit(actor, "period.completed", period, notes=notes)
    return period
