# Generated by Django 5.1.15 on 2026-09-24 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("holiday", "Holiday"), ("wfh", "WFH"), ("event", "Event")],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["date", "id"],
            },
        ),
        migrations.CreateModel(
            name="RecurringWfhRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        help_text="0 = Sunday ... 6 = Saturday, matching WEEKDAY_NAMES.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=200)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["weekday", "id"],
            },
        ),
    ]
