# Generated by Django 5.1.15 on 2026-09-25 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('employees', '0004_org_structure_and_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(editable=False, max_length=12, unique=True)),
                ('category', models.CharField(choices=[('Regular', 'Regular'), ('Compensatory offs', 'Compensatory offs'), ('Unpaid', 'Unpaid'), ('Incident based', 'Incident based')], default='Regular', max_length=30)),
                ('annual_allocation', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('carry_forward_limit', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('requires_approval', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('half_day_option', models.CharField(choices=[('full_day', 'Full day'), ('first_half', 'First half'), ('second_half', 'Second half')], default='full_day', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='submitted', max_length=20)),
                ('duration_days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('financial_year', models.CharField(max_length=4)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='approvals.request')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='leave.leavetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=4)),
                ('opening_balance', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('allocated', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('used', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('pending', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('carry_forward', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('lapsed', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='leave.leavetype')),
            ],
            options={
                'ordering': ['leave_type__name'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'leave_type', 'financial_year'), name='unique_leave_balance_per_employee_type_year')],
            },
        ),
    ]
