# Generated by Django 5.0.14 on 2026-09-17 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('onboarding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('contract', 'Contract'), ('intern', 'Intern')], default='full_time', max_length=20)),
                ('probation_period_months', models.PositiveSmallIntegerField(default=3)),
                ('notice_period_days', models.PositiveSmallIntegerField(default=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter', to='onboarding.onboardingprofile')),
            ],
        ),
    ]
