# Generated by Django 5.0.14 on 2026-09-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_offerlettertemplate_offerletter_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettertemplate',
            name='source_docx',
            field=models.FileField(blank=True, null=True, upload_to='offer_letter_templates/'),
        ),
        migrations.AlterField(
            model_name='offerlettertemplate',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
