# Generated by Django 5.0.14 on 2026-09-17 14:56

from django.db import migrations, models


def backfill_basic_salary(apps, schema_editor):
    """Existing offer letters (from before the salary-breakdown split) have
    a real `annual_ctc` but zeroed-out component fields. OfferLetter.save()
    now always recomputes annual_ctc as the sum of the four components —
    without this backfill, the next save of an old row would silently zero
    out its historical CTC. Bucket the whole existing total into
    basic_salary so the sum still equals what it always was."""
    OfferLetter = apps.get_model('onboarding', 'OfferLetter')
    OfferLetter.objects.filter(basic_salary=0).update(basic_salary=models.F('annual_ctc'))


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_offerlettertemplate_source_docx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='other_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='other_components',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(backfill_basic_salary, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='offerletter',
            name='annual_ctc',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
