# Generated by Django 5.0.14 on 2026-09-17 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def deactivate_manual_bgv_checkbox_and_backfill(apps, schema_editor):
    """The old seeded 'Complete background verification' checklist item was
    a manual HR checkbox with nothing real behind it. Superseded by the new
    BackgroundVerification record, which derives its status automatically
    from the Submit-ID/education/employment-document tasks instead."""
    OnboardingTaskTemplate = apps.get_model('onboarding', 'OnboardingTaskTemplate')
    OnboardingTask = apps.get_model('onboarding', 'OnboardingTask')
    OnboardingProfile = apps.get_model('onboarding', 'OnboardingProfile')
    BackgroundVerification = apps.get_model('onboarding', 'BackgroundVerification')

    OnboardingTaskTemplate.objects.filter(
        title__iexact='Complete background verification', is_active=True,
    ).update(is_active=False)
    # is_required=False too: a required-but-skipped task would otherwise
    # permanently sit in every affected hire's progress denominator with no
    # way to ever reach 100%.
    OnboardingTask.objects.filter(
        title__iexact='Complete background verification',
    ).exclude(status='done').update(status='skipped', is_required=False)

    for profile in OnboardingProfile.objects.all():
        doc_tasks = list(profile.tasks.filter(requires_document=True))
        if not doc_tasks:
            continue
        all_submitted = all(t.status == 'done' for t in doc_tasks)
        BackgroundVerification.objects.get_or_create(
            profile=profile,
            defaults={'status': 'ready_for_review' if all_submitted else 'pending_documents'},
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_offerletter_basic_salary_offerletter_hra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('pending_documents', 'Pending documents'), ('ready_for_review', 'Ready for review'), ('passed', 'Passed'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background_verification', to='onboarding.onboardingprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(deactivate_manual_bgv_checkbox_and_backfill, noop),
    ]
