# Generated by Django 5.1.15 on 2026-09-22 20:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0004_org_structure_and_lifecycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaySchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("semimonthly", "Semi-monthly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pay_period_start_day",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ]
                    ),
                ),
                (
                    "cutoff_day",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ]
                    ),
                ),
                ("pay_date_offset_days", models.IntegerField(default=3)),
                ("first_cycle_start_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SalaryComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "component_type",
                    models.CharField(
                        choices=[("earning", "Earning"), ("deduction", "Deduction")], max_length=20
                    ),
                ),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Amount"),
                            ("percentage_of_basic", "Percentage of Basic"),
                            ("formula", "Formula"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "formula_expr",
                    models.TextField(blank=True, help_text="Formula for 'formula' type", null=True),
                ),
                (
                    "default_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("is_taxable", models.BooleanField(default=True)),
                ("is_statutory", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["component_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeBenefit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "benefit_type",
                    models.CharField(
                        choices=[
                            ("health_insurance", "Health Insurance"),
                            ("retirement", "Retirement"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("provider", models.CharField(blank=True, max_length=255)),
                (
                    "employee_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "employer_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("effective_from", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_benefits",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["employee", "benefit_type"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeDeduction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "deduction_type",
                    models.CharField(
                        choices=[("loan", "Loan"), ("advance", "Advance"), ("custom", "Custom")],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("installment_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("installments_remaining", models.IntegerField(default=0)),
                ("start_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_deductions",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["employee", "start_date"],
            },
        ),
        migrations.CreateModel(
            name="EmployeePaymentInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("direct_deposit", "Direct Deposit"),
                            ("cash", "Cash"),
                            ("paper_check", "Paper Check"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255)),
                ("bank_account_number", models.CharField(blank=True, max_length=50)),
                ("bank_ifsc_code", models.CharField(blank=True, max_length=11)),
                ("bank_account_holder_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_payment_info",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Employee Payment Info",
                "ordering": ["employee"],
            },
        ),
        migrations.CreateModel(
            name="EmployeePayrollStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_payroll_enabled", models.BooleanField(default=True)),
                ("disabled_reason", models.TextField(blank=True, null=True)),
                ("effective_from", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_status",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Employee Payroll Status",
                "ordering": ["employee"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeStatutoryInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pan_number", models.CharField(max_length=10, unique=True)),
                ("pf_number", models.CharField(blank=True, max_length=50)),
                ("esi_number", models.CharField(blank=True, max_length=50)),
                ("lwf_applicable", models.BooleanField(default=False)),
                ("professional_tax_state", models.CharField(blank=True, max_length=2)),
                ("professional_tax_exempt", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_statutory_info",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Employee Statutory Info",
                "ordering": ["employee"],
            },
        ),
        migrations.CreateModel(
            name="LegalEntityPayrollProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pan", models.CharField(max_length=10, unique=True)),
                ("tan", models.CharField(blank=True, max_length=10, null=True)),
                ("gstin", models.CharField(blank=True, max_length=15, null=True)),
                ("state", models.CharField(max_length=2)),
                ("address", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legal_entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_profile",
                        to="employees.legalentity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayStubTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "applies_to",
                    models.CharField(
                        choices=[("employee", "Employee"), ("contractor", "Contractor")],
                        max_length=20,
                    ),
                ),
                ("layout_json", models.JSONField(default=dict)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("email", "Email"), ("portal", "Portal"), ("both", "Both")],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_default", "name"],
                "unique_together": {("name", "applies_to")},
            },
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("min_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("max_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_structures",
                        to="employees.legalentity",
                    ),
                ),
            ],
            options={
                "ordering": ["legal_entity", "name"],
                "unique_together": {("legal_entity", "name")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeCompensation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "fixed_monthly_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_contractor", models.BooleanField(default=False)),
                (
                    "contractor_rate_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fixed", "Fixed"),
                            ("hourly", "Hourly"),
                            ("variable", "Variable"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "contractor_rate",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("effective_from", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_compensation",
                        to="employees.employee",
                    ),
                ),
                (
                    "salary_structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payroll.salarystructure",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Employee Compensation",
                "ordering": ["employee"],
            },
        ),
        migrations.CreateModel(
            name="TaxFilingConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "filing_frequency",
                    models.CharField(
                        choices=[
                            ("quarterly", "Quarterly"),
                            ("half_yearly", "Half Yearly"),
                            ("annual", "Annual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("state_tax_id", models.CharField(blank=True, max_length=50, null=True)),
                ("federal_tax_id", models.CharField(blank=True, max_length=50, null=True)),
                ("effective_from", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legal_entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_filing_config",
                        to="employees.legalentity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tax Filing Configs",
            },
        ),
        migrations.CreateModel(
            name="PayrollOvertimeAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pay_period_month", models.DateField()),
                ("overtime_hours", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                (
                    "overtime_rate_multiplier",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=4),
                ),
                (
                    "leave_adjustment_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_overtime_adjustments",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-pay_period_month"],
                "unique_together": {("employee", "pay_period_month")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeVariablePay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("pay_month", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compensation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variable_pays",
                        to="payroll.employeecompensation",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="payroll.salarycomponent"
                    ),
                ),
            ],
            options={
                "ordering": ["-pay_month"],
                "unique_together": {("compensation", "component", "pay_month")},
            },
        ),
        migrations.CreateModel(
            name="PayGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("maker_checker_enabled", models.BooleanField(default=True)),
                (
                    "approval_threshold_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_approver_groups",
                        to="employees.employee",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pay_groups",
                        to="employees.legalentity",
                    ),
                ),
                (
                    "pay_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="payroll.payschedule"
                    ),
                ),
                (
                    "default_salary_structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payroll.salarystructure",
                    ),
                ),
            ],
            options={
                "ordering": ["legal_entity", "name"],
                "unique_together": {("legal_entity", "name")},
            },
        ),
        migrations.CreateModel(
            name="SalaryStructureComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "value_override",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="payroll.salarycomponent"
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="payroll.salarystructure",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("structure", "component")},
            },
        ),
        migrations.CreateModel(
            name="StatutoryConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "contribution_type",
                    models.CharField(
                        choices=[
                            ("PF", "Provident Fund"),
                            ("ESI", "Employee State Insurance"),
                            ("LWF", "Labor Welfare Fund"),
                            ("PROFESSIONAL_TAX", "Professional Tax"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("registration_number", models.CharField(max_length=50)),
                ("effective_date", models.DateField()),
                ("signatory_name", models.CharField(max_length=255)),
                ("signatory_designation", models.CharField(max_length=100)),
                ("signatory_pan", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statutory_configs",
                        to="employees.legalentity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Statutory Configs",
                "ordering": ["legal_entity", "contribution_type"],
                "unique_together": {("legal_entity", "contribution_type")},
            },
        ),
    ]
