# Generated by Django 5.1.15 on 2026-09-24 06:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_user'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LopConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_basis', models.CharField(choices=[('fixed_30', 'Fixed 30 Days'), ('calendar_days', 'Calendar Days'), ('working_days', 'Working Days')], default='fixed_30', max_length=20)),
                ('effective_from', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lop_config', to='employees.legalentity')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('bonus', 'Bonus'), ('dip', 'DIP'), ('retention', 'Retention'), ('arrear', 'Arrear'), ('reimbursement', 'Reimbursement'), ('recovery', 'Recovery'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('one_time', 'One Time'), ('recurring', 'Recurring')], default='one_time', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_taxable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to='employees.employee')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('working_days', models.IntegerField(default=30)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='employees.legalentity')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('legal_entity', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('completed', 'Completed'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('processed_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('total_net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_created', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PfRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_pf_rate', models.DecimalField(decimal_places=2, default=12.0, help_text='Employee PF %', max_digits=5)),
                ('employer_pf_rate', models.DecimalField(decimal_places=2, default=12.0, help_text='Employer PF %', max_digits=5)),
                ('pf_wage_ceiling', models.DecimalField(blank=True, decimal_places=2, help_text='Max salary for PF calculation', max_digits=12, null=True)),
                ('pf_basis', models.CharField(default='basic', help_text='Basis: basic, basic+da, configured_wage', max_length=50)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('effective_from', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pf_rule', to='employees.legalentity')),
            ],
        ),
        migrations.CreateModel(
            name='TdsConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_regime', models.CharField(choices=[('old', 'Old Regime'), ('new', 'New Regime')], default='new', max_length=20)),
                ('financial_year', models.CharField(max_length=10)),
                ('tds_rules', models.JSONField(default=dict)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tds_config', to='employees.legalentity')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earnings_json', models.JSONField(default=dict)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('working_days', models.IntegerField(default=0)),
                ('lop_days', models.IntegerField(default=0)),
                ('lop_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_after_lop', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions_json', models.JSONField(default=dict)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjustments_json', models.JSONField(default=dict)),
                ('total_adjustments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('previous_net_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_results', to='employees.employee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['-run__created_at', 'employee'],
                'unique_together': {('run', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='PtSlab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salary_from', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pt_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt_slabs', to='employees.legalentity')),
            ],
            options={
                'ordering': ['legal_entity', 'salary_from'],
                'unique_together': {('legal_entity', 'salary_from', 'salary_to', 'effective_from')},
            },
        ),
    ]
