# Generated by Django 5.1.15 on 2026-09-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_user'),
        ('employees', '0007_seed_org_masters'),
    ]

    operations = [
    ]
