from django.urls import path

from . import views

urlpatterns = [
    path('access-grants', views.AccessGrantListView.as_view(), name='onboarding-access-grants'),
    path('access-grants/<int:pk>', views.AccessGrantDetailView.as_view(), name='onboarding-access-grant-detail'),
    path('work', views.MyOnboardingWorkView.as_view(), name='onboarding-work'),
    path('records', views.OnboardingRecordListView.as_view(), name='onboarding-record-list'),
    path('records/<int:pk>', views.OnboardingRecordDetailView.as_view(), name='onboarding-record-detail'),
    path('records/<int:pk>/activate', views.OnboardingRecordActivateView.as_view(), name='onboarding-record-activate'),
    path('records/<int:pk>/complete', views.OnboardingRecordCompleteView.as_view(), name='onboarding-record-complete'),
    path('records/<int:pk>/tasks', views.OnboardingRecordTasksView.as_view(), name='onboarding-record-tasks'),
    path('records/<int:pk>/offer-letter', views.OfferLetterDetailView.as_view(), name='onboarding-offer-letter'),
    path('records/<int:pk>/offer-letter/send', views.OfferLetterSendView.as_view(), name='onboarding-offer-letter-send'),
    path('records/<int:pk>/offer-letter/resend', views.OfferLetterResendView.as_view(), name='onboarding-offer-letter-resend'),
    path('records/<int:pk>/offer-letter/extend', views.OfferLetterExtendView.as_view(), name='onboarding-offer-letter-extend'),
    path('records/<int:pk>/offer-letter/cancel', views.OfferLetterCancelView.as_view(), name='onboarding-offer-letter-cancel'),
    path('records/<int:pk>/background-verification', views.BackgroundVerificationDetailView.as_view(), name='onboarding-bgv-detail'),
    path('records/<int:pk>/bank-details', views.BankDetailsDetailView.as_view(), name='onboarding-bank-details-detail'),
    path('records/<int:pk>/identity-documents', views.IdentityDocumentsDetailView.as_view(), name='onboarding-identity-documents-detail'),
    path('records/<int:pk>/education-records', views.EducationRecordsDetailView.as_view(), name='onboarding-education-records-detail'),
    path('records/<int:pk>/employee-letters', views.EmployeeLettersDetailView.as_view(), name='onboarding-employee-letters-detail'),
    path('records/<int:pk>/documents/download-all', views.OnboardingDocumentsDownloadAllView.as_view(), name='onboarding-documents-download-all'),
    path('tasks/<int:pk>', views.OnboardingTaskDetailView.as_view(), name='onboarding-task-detail'),
    path('identity-documents/<int:pk>/verify', views.IdentityDocumentVerifyView.as_view(), name='onboarding-identity-document-verify'),
    path('education-records/<int:pk>/verify', views.EducationRecordVerifyView.as_view(), name='onboarding-education-record-verify'),
    path('me', views.MyOnboardingView.as_view(), name='onboarding-me'),
    path('me/bank-details', views.MyBankDetailsView.as_view(), name='onboarding-my-bank-details'),
    path('me/identity-documents', views.MyIdentityDocumentsView.as_view(), name='onboarding-my-identity-documents'),
    path('me/identity-documents/<int:pk>', views.MyIdentityDocumentDetailView.as_view(), name='onboarding-my-identity-document-detail'),
    path('me/education-records', views.MyEducationRecordsView.as_view(), name='onboarding-my-education-records'),
    path('me/education-records/<int:pk>', views.MyEducationRecordDetailView.as_view(), name='onboarding-my-education-record-detail'),
    path('me/employee-letters', views.MyEmployeeLettersView.as_view(), name='onboarding-my-employee-letters'),
    path('me/documents-overview', views.MyDocumentsOverviewView.as_view(), name='onboarding-my-documents-overview'),
    path('templates', views.OnboardingTaskTemplateListView.as_view(), name='onboarding-template-list'),
    path('templates/<int:pk>', views.OnboardingTaskTemplateDetailView.as_view(), name='onboarding-template-detail'),
    path('offer-letter-templates', views.OfferLetterTemplateListView.as_view(), name='onboarding-offer-letter-template-list'),
    path('offer-letter-templates/<int:pk>', views.OfferLetterTemplateDetailView.as_view(), name='onboarding-offer-letter-template-detail'),
]
